Repository KAU-Capstone-ONDA/ONDA-BE, pull requests merged in 2024-06, with the labels that each got.

#29 feat: Swagger 적용
  build.gradle
  src/main/java/com/capstone/onda/global/config/SwaggerConfig.java
Labels: 🛠️ feature

#45 Feature/#35 create enum type
  src/main/java/com/capstone/onda/domain/roomType/EnumDTO.java
  src/main/java/com/capstone/onda/domain/roomType/EnumManager.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/amenity/AmenityConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/amenity/AmenityGroup.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/amenity/AmenityOption.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/attraction/AttractionConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/attraction/AttractionOption.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/facility/FacilityConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/facility/FacilityOption.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/roomType/RoomTypeCategory.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/roomType/RoomTypeCategoryConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/service/ServiceConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/service/ServiceOption.java
Labels: 🛠️ feature

#48 Feature/#26 create room type create api
  src/main/java/com/capstone/onda/domain/hotel/entity/Hotel.java
  src/main/java/com/capstone/onda/domain/hotel/exception/HotelNotFound.java
  src/main/java/com/capstone/onda/domain/hotel/repository/HotelRepository.java
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/dto/request/RoomTypeRequest.java
  src/main/java/com/capstone/onda/domain/roomType/entity/RoomType.java
  src/main/java/com/capstone/onda/domain/roomType/repository/RoomTypeRepository.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
  src/main/java/com/capstone/onda/global/exception/ErrorCode.java
Labels: 🛠️ feature

#49 Feature/#31 create room type get one api
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypeResponse.java
  src/main/java/com/capstone/onda/domain/roomType/exception/RoomTypeNotFound.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
  src/main/java/com/capstone/onda/domain/roomType/util/RoomTypeMapper.java
  src/main/java/com/capstone/onda/global/exception/ErrorCode.java
Labels: 🛠️ feature

#50 Feature/#25 create sign up reversion
  build.gradle
  src/main/java/com/capstone/onda/domain/hotel/util/HotelMapper.java
  src/main/java/com/capstone/onda/domain/member/controller/MemberRestController.java
  src/main/java/com/capstone/onda/domain/member/dto/request/MemberSignUpRequest.java
  src/main/java/com/capstone/onda/domain/member/dto/response/MemberResponse.java
  src/main/java/com/capstone/onda/domain/member/entity/Member.java
  src/main/java/com/capstone/onda/domain/member/entity/ProviderType.java
  src/main/java/com/capstone/onda/domain/member/exception/AlreadyExistEmailException.java
  src/main/java/com/capstone/onda/domain/member/exception/InvalidHotelException.java
  src/main/java/com/capstone/onda/domain/member/exception/InvalidProviderTypeException.java
  src/main/java/com/capstone/onda/domain/member/service/MemberService.java
  src/main/java/com/capstone/onda/domain/member/util/MemberMapper.java
  src/main/java/com/capstone/onda/domain/member/validation/ValidationGroups.java
  src/main/java/com/capstone/onda/domain/member/validation/ValidationSequence.java
  src/main/java/com/capstone/onda/global/exception/ErrorCode.java
  src/main/java/com/capstone/onda/global/security/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/capstone/onda/global/security/service/OAuthService.java
  src/main/resources/application-local.yml
Labels: 🛠️ feature

#54 feat: 객실타입 리스트 조회 컨트롤러 및 서비스, 응답 DTO 구현
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypeListResponse.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
Labels: 🛠️ feature

#55 feat: 객실타입 수정 컨트롤러 및 서비스, 수정 DTO 구현
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/dto/request/RoomTypeEdit.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
Labels: 🛠️ feature

#58 feat: 객실타입 삭제 컨트롤러 및 서비스 구현
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
Labels: 🛠️ feature

#60 Feature/#57 create room typewith member
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypePostResponse.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
  src/main/java/com/capstone/onda/domain/roomType/util/RoomTypeMapper.java
  src/main/java/com/capstone/onda/global/security/util/JwtUtil.java
  src/test/resources/application.yml
Labels: 🛠️ feature, 🚧 refactoring

#56 Bugfix/#51 fix login uri
  src/main/java/com/capstone/onda/global/security/filter/JwtAuthFilter.java
  src/main/java/com/capstone/onda/global/security/filter/JwtExceptionFilter.java
  src/main/java/com/capstone/onda/global/security/handler/OAuthAuthenticationSuccessHandler.java
Labels: :lady_beetle: bug, 🛠️ feature, 🚧 refactoring

#65 Feature/#64 create post competing hotel api
  src/main/java/com/capstone/onda/domain/hotel/controller/HotelRestController.java
  src/main/java/com/capstone/onda/domain/hotel/dto/request/CompetingHotelRequest.java
  src/main/java/com/capstone/onda/domain/hotel/entity/Hotel.java
  src/main/java/com/capstone/onda/domain/hotel/service/HotelService.java
Labels: 🛠️ feature

#67 Feature/#66 create mock user
  src/test/java/com/capstone/onda/mock/WithCustomMockUser.java
  src/test/java/com/capstone/onda/mock/WithCustomMockUserSecurityContextFactory.java
  src/test/resources/application.yml
Labels: 🛠️ feature

#70 feat: jwtExceptionFilter 수정
  src/main/java/com/capstone/onda/global/security/filter/JwtExceptionFilter.java
Labels: :lady_beetle: bug, 🛠️ feature

#76 fix: CorsConfig 세팅
  src/main/java/com/capstone/onda/global/config/SecurityConfig.java
Labels: :lady_beetle: bug

#78 feat: Swagger에 Auth Header 추가
  src/main/java/com/capstone/onda/global/config/SwaggerConfig.java
Labels: 🛠️ feature

#80 feat: 객실타입에 투숙인원 추가로 인한 수정
  src/main/java/com/capstone/onda/domain/roomType/dto/request/RoomTypeRequest.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypeEditResponse.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypeListResponse.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypePostResponse.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypeResponse.java
  src/main/java/com/capstone/onda/domain/roomType/entity/RoomType.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
  src/main/java/com/capstone/onda/domain/roomType/util/RoomTypeMapper.java
Labels: 🛠️ feature

#84 fix: 내 호텔의 모든 경쟁 업체 조회 Response Data 변경
  src/main/java/com/capstone/onda/domain/hotel/controller/HotelRestController.java
  src/main/java/com/capstone/onda/domain/hotel/dto/response/HotelOnlyResponse.java
  src/main/java/com/capstone/onda/domain/hotel/service/HotelService.java
  src/main/java/com/capstone/onda/domain/hotel/util/HotelMapper.java
Labels: 🚧 refactoring

#86 fix: mysql 글씨 깨짐 현상 해결 및 객실타입 수정 관련 코드를 수정
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/dto/response/RoomTypeListResponse.java
  src/main/java/com/capstone/onda/domain/roomType/entity/RoomType.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/amenity/AmenityConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/amenity/AmenityOption.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/attraction/AttractionConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/attraction/AttractionOption.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/facility/FacilityConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/facility/FacilityOption.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/service/ServiceConverter.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/service/ServiceOption.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
  src/main/java/com/capstone/onda/domain/roomType/util/RoomTypeMapper.java
Labels: 🚧 refactoring

#90 feat: 프론트측 요구에 따른 AmenityGroup 삭제
  src/main/java/com/capstone/onda/domain/roomType/dto/request/RoomTypeRequest.java
  src/main/java/com/capstone/onda/domain/roomType/enumeration/amenity/AmenityGroup.java
Labels: 🚧 refactoring

#94 Bugfix/#93 fix jwt logic
  src/main/java/com/capstone/onda/domain/hotel/controller/HotelRestController.java
  src/main/java/com/capstone/onda/global/config/SwaggerConfig.java
  src/main/java/com/capstone/onda/global/security/dto/CustomOAuth2User.java
  src/main/java/com/capstone/onda/global/security/dto/SecurityUser.java
  src/main/java/com/capstone/onda/global/security/filter/JwtAuthFilter.java
  src/main/java/com/capstone/onda/global/security/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/capstone/onda/global/security/service/OAuthService.java
  src/main/java/com/capstone/onda/global/security/util/JwtUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :lady_beetle: bug, 🛠️ feature

#96 fix: roomType api CustomOAuthUser로 모두 변경
  src/main/java/com/capstone/onda/domain/roomType/controller/RoomTypeController.java
  src/main/java/com/capstone/onda/domain/roomType/service/RoomTypeService.java
Labels: :lady_beetle: bug, 🛠️ feature

#101 fix: jwt access token 시간 추가
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :lady_beetle: bug, 🛠️ feature
